name: sdurian
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: Poppins
      fonts:
      - asset: lib/fonts/Poppins/Poppins-Black.ttf
        weight: 900
      - asset: lib/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: lib/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: lib/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: lib/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: lib/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: lib/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: lib/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: lib/fonts/Poppins/Poppins-Thin.ttf
        weight: 100
