name: sdurian
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.1
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  crypto: ^3.0.3
  random_string: ^2.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/durian_king.png
  android: true
  android_12:
    image: lib/assets/durian_king.png

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/PoodakMenu/DurianDessert/
    - lib/assets/PoodakMenu/MenuDooren/
    - lib/assets/PoodakMenu/MenuPaketNasi/
    - lib/assets/PoodakMenu/Rekomendasi/
    - lib/assets/PoodakMenu/SiomayPempek/
    - lib/icons/
  fonts:
    - family: Poppins
      fonts:
      - asset: lib/fonts/Poppins/Poppins-Black.ttf
        weight: 900
      - asset: lib/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: lib/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: lib/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: lib/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: lib/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: lib/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: lib/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: lib/fonts/Poppins/Poppins-Thin.ttf
        weight: 100
